# Generated by Django 5.0 on 2023-12-21 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('time', models.DateTimeField()),
                ('side1RankingPoints', models.IntegerField(default=0)),
                ('side2RankingPoints', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('ranking_points', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.IntegerField(unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('side1', models.CharField(max_length=100)),
                ('side2', models.CharField(max_length=100)),
                ('matches', models.ManyToManyField(to='tournament_site.matches')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('number_of_teams', models.IntegerField(default=0)),
                ('teams', models.ManyToManyField(to='tournament_site.team')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='side1Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side1Team', to='tournament_site.team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='side2Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side2Team', to='tournament_site.team'),
        ),
    ]
