# Generated by Django 5.0.6 on 2024-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='display_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
