# Generated by Django 5.0 on 2023-12-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='matches',
            field=models.ManyToManyField(blank=True, to='tournament_site.matches'),
        ),
    ]
