# Generated by Django 6.0.1 on 2026-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_site', '0002_matches_display_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='coop_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='coop_points',
            field=models.IntegerField(default=0),
        ),
    ]
