# Generated by Django 5.0 on 2023-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_site', '0003_alter_matches_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
